version: '3.8'

services:
  raft-node1:
    build: .
    container_name: raft-node1
    networks:
      - raft-network
    ports:
      - "8001:8001"
    volumes:
      - raft-data-node1:/data/raft  # Volume untuk raft-node1
    command: ["java", "-cp", "target/raft-1.0-SNAPSHOT-jar-with-dependencies.jar", "com.raft.RaftServer", "raft-node1", "8001", "FOLLOWER"]

  raft-node2:
    build: .
    container_name: raft-node2
    networks:
      - raft-network
    ports:
      - "8002:8002"
    volumes:
      - raft-data-node2:/data/raft  # Volume untuk raft-node2
    command: ["java", "-cp", "target/raft-1.0-SNAPSHOT-jar-with-dependencies.jar", "com.raft.RaftServer", "raft-node2", "8002", "FOLLOWER"]

  raft-node3:
    build: .
    container_name: raft-node3
    networks:
      - raft-network
    ports:
      - "8003:8003"
    volumes:
      - raft-data-node3:/data/raft  # Volume untuk raft-node3
    command: ["java", "-cp", "target/raft-1.0-SNAPSHOT-jar-with-dependencies.jar", "com.raft.RaftServer", "raft-node3", "8003", "FOLLOWER"]

  raft-node4:
    build: .
    container_name: raft-node4
    networks:
      - raft-network
    ports:
      - "8004:8004"
    volumes:
      - raft-data-node4:/data/raft  # Volume untuk raft-node4
    command: ["java", "-cp", "target/raft-1.0-SNAPSHOT-jar-with-dependencies.jar", "com.raft.RaftServer", "raft-node4", "8004", "FOLLOWER"]

  raft-client1: # Mengubah nama dari raft-client menjadi raft-client1
    build: .
    container_name: raft-client1
    networks:
      - raft-network
    depends_on:
      - raft-node1
      - raft-node2
      - raft-node3
      - raft-node4
    command: ["java", "-cp", "target/raft-1.0-SNAPSHOT-jar-with-dependencies.jar", "com.raft.Main", "raft-node1", "8001"]
    stdin_open: true
    tty: true

  raft-client2: # Menambahkan container client kedua
    build: .
    container_name: raft-client2
    networks:
      - raft-network
    depends_on:
      - raft-node1
      - raft-node2
      - raft-node3
      - raft-node4
    # Anda mungkin ingin client kedua terhubung ke node yang berbeda atau sama
    command: ["java", "-cp", "target/raft-1.0-SNAPSHOT-jar-with-dependencies.jar", "com.raft.Main", "raft-node2", "8002"]
    stdin_open: true
    tty: true

networks:
  raft-network:
    driver: bridge

volumes: # Definisi volume di tingkat atas
  raft-data-node1:
    driver: local
  raft-data-node2:
    driver: local
  raft-data-node3:
    driver: local
  raft-data-node4:
    driver: local